//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosUnityMessages
{
    [Serializable]
    public class GripperControlMsg : Message
    {
        public const string k_RosMessageName = "ros_unity_messages/GripperControl";
        public override string RosMessageName => k_RosMessageName;

        public double gripper_angle;

        public GripperControlMsg()
        {
            this.gripper_angle = 0.0;
        }

        public GripperControlMsg(double gripper_angle)
        {
            this.gripper_angle = gripper_angle;
        }

        public static GripperControlMsg Deserialize(MessageDeserializer deserializer) => new GripperControlMsg(deserializer);

        private GripperControlMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.gripper_angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.gripper_angle);
        }

        public override string ToString()
        {
            return "GripperControlMsg: " +
            "\ngripper_angle: " + gripper_angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
