//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosUnityMessages
{
    [Serializable]
    public class UnityRequestMsg : Message
    {
        public const string k_RosMessageName = "ros_unity_messages/UnityRequest";
        public override string RosMessageName => k_RosMessageName;

        public Std.StringMsg scene_name;
        public Geometry.PoseMsg pre_pick_location;
        public Geometry.PoseMsg pre_place_location;
        public Geometry.PoseMsg pick_location;
        public Geometry.PoseMsg place_location;
        public UnityObjectMsg[] static_objects;

        public UnityRequestMsg()
        {
            this.scene_name = new Std.StringMsg();
            this.pre_pick_location = new Geometry.PoseMsg();
            this.pre_place_location = new Geometry.PoseMsg();
            this.pick_location = new Geometry.PoseMsg();
            this.place_location = new Geometry.PoseMsg();
            this.static_objects = new UnityObjectMsg[0];
        }

        public UnityRequestMsg(Std.StringMsg scene_name, Geometry.PoseMsg pre_pick_location, Geometry.PoseMsg pre_place_location, Geometry.PoseMsg pick_location, Geometry.PoseMsg place_location, UnityObjectMsg[] static_objects)
        {
            this.scene_name = scene_name;
            this.pre_pick_location = pre_pick_location;
            this.pre_place_location = pre_place_location;
            this.pick_location = pick_location;
            this.place_location = place_location;
            this.static_objects = static_objects;
        }

        public static UnityRequestMsg Deserialize(MessageDeserializer deserializer) => new UnityRequestMsg(deserializer);

        private UnityRequestMsg(MessageDeserializer deserializer)
        {
            this.scene_name = Std.StringMsg.Deserialize(deserializer);
            this.pre_pick_location = Geometry.PoseMsg.Deserialize(deserializer);
            this.pre_place_location = Geometry.PoseMsg.Deserialize(deserializer);
            this.pick_location = Geometry.PoseMsg.Deserialize(deserializer);
            this.place_location = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.static_objects, UnityObjectMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.scene_name);
            serializer.Write(this.pre_pick_location);
            serializer.Write(this.pre_place_location);
            serializer.Write(this.pick_location);
            serializer.Write(this.place_location);
            serializer.WriteLength(this.static_objects);
            serializer.Write(this.static_objects);
        }

        public override string ToString()
        {
            return "UnityRequestMsg: " +
            "\nscene_name: " + scene_name.ToString() +
            "\npre_pick_location: " + pre_pick_location.ToString() +
            "\npre_place_location: " + pre_place_location.ToString() +
            "\npick_location: " + pick_location.ToString() +
            "\nplace_location: " + place_location.ToString() +
            "\nstatic_objects: " + System.String.Join(", ", static_objects.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
