//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosUnityMessages
{
    [Serializable]
    public class UnityRequestMsg : Message
    {
        public const string k_RosMessageName = "ros_unity_messages/UnityRequest";
        public override string RosMessageName => k_RosMessageName;

        public double[] joints;
        public Geometry.PoseMsg pick_pose;
        public Geometry.PoseMsg place_pose;
        public UnityObjectMsg[] static_objects;

        public UnityRequestMsg()
        {
            this.joints = new double[6];
            this.pick_pose = new Geometry.PoseMsg();
            this.place_pose = new Geometry.PoseMsg();
            this.static_objects = new UnityObjectMsg[0];
        }

        public UnityRequestMsg(double[] joints, Geometry.PoseMsg pick_pose, Geometry.PoseMsg place_pose, UnityObjectMsg[] static_objects)
        {
            this.joints = joints;
            this.pick_pose = pick_pose;
            this.place_pose = place_pose;
            this.static_objects = static_objects;
        }

        public static UnityRequestMsg Deserialize(MessageDeserializer deserializer) => new UnityRequestMsg(deserializer);

        private UnityRequestMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(double), 6);
            this.pick_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.place_pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.static_objects, UnityObjectMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
            serializer.Write(this.pick_pose);
            serializer.Write(this.place_pose);
            serializer.WriteLength(this.static_objects);
            serializer.Write(this.static_objects);
        }

        public override string ToString()
        {
            return "UnityRequestMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\npick_pose: " + pick_pose.ToString() +
            "\nplace_pose: " + place_pose.ToString() +
            "\nstatic_objects: " + System.String.Join(", ", static_objects.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
