//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosUnityMessages
{
    [Serializable]
    public class UnityObjectMsg : Message
    {
        public const string k_RosMessageName = "ros_unity_messages/UnityObject";
        public override string RosMessageName => k_RosMessageName;

        public Std.StringMsg id;
        public Geometry.PointMsg position;
        public Geometry.QuaternionMsg orientation;
        public Geometry.Vector3Msg scale;

        public UnityObjectMsg()
        {
            this.id = new Std.StringMsg();
            this.position = new Geometry.PointMsg();
            this.orientation = new Geometry.QuaternionMsg();
            this.scale = new Geometry.Vector3Msg();
        }

        public UnityObjectMsg(Std.StringMsg id, Geometry.PointMsg position, Geometry.QuaternionMsg orientation, Geometry.Vector3Msg scale)
        {
            this.id = id;
            this.position = position;
            this.orientation = orientation;
            this.scale = scale;
        }

        public static UnityObjectMsg Deserialize(MessageDeserializer deserializer) => new UnityObjectMsg(deserializer);

        private UnityObjectMsg(MessageDeserializer deserializer)
        {
            this.id = Std.StringMsg.Deserialize(deserializer);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            this.orientation = Geometry.QuaternionMsg.Deserialize(deserializer);
            this.scale = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.position);
            serializer.Write(this.orientation);
            serializer.Write(this.scale);
        }

        public override string ToString()
        {
            return "UnityObjectMsg: " +
            "\nid: " + id.ToString() +
            "\nposition: " + position.ToString() +
            "\norientation: " + orientation.ToString() +
            "\nscale: " + scale.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
