//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosUnityMessages
{
    [Serializable]
    public class UnityDynamicObjectsMsg : Message
    {
        public const string k_RosMessageName = "ros_unity_messages/UnityDynamicObjects";
        public override string RosMessageName => k_RosMessageName;

        public UnityObjectMsg[] dynamic_objs;

        public UnityDynamicObjectsMsg()
        {
            this.dynamic_objs = new UnityObjectMsg[0];
        }

        public UnityDynamicObjectsMsg(UnityObjectMsg[] dynamic_objs)
        {
            this.dynamic_objs = dynamic_objs;
        }

        public static UnityDynamicObjectsMsg Deserialize(MessageDeserializer deserializer) => new UnityDynamicObjectsMsg(deserializer);

        private UnityDynamicObjectsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.dynamic_objs, UnityObjectMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.dynamic_objs);
            serializer.Write(this.dynamic_objs);
        }

        public override string ToString()
        {
            return "UnityDynamicObjectsMsg: " +
            "\ndynamic_objs: " + System.String.Join(", ", dynamic_objs.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
