//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RtdeEcho
{
    [Serializable]
    public class RtdeDataMsg : Message
    {
        public const string k_RosMessageName = "rtde_echo/RtdeData";
        public override string RosMessageName => k_RosMessageName;

        public double energy_consumed;
        public double braking_energy_dissipated;

        public RtdeDataMsg()
        {
            this.energy_consumed = 0.0;
            this.braking_energy_dissipated = 0.0;
        }

        public RtdeDataMsg(double energy_consumed, double braking_energy_dissipated)
        {
            this.energy_consumed = energy_consumed;
            this.braking_energy_dissipated = braking_energy_dissipated;
        }

        public static RtdeDataMsg Deserialize(MessageDeserializer deserializer) => new RtdeDataMsg(deserializer);

        private RtdeDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.energy_consumed);
            deserializer.Read(out this.braking_energy_dissipated);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.energy_consumed);
            serializer.Write(this.braking_energy_dissipated);
        }

        public override string ToString()
        {
            return "RtdeDataMsg: " +
            "\nenergy_consumed: " + energy_consumed.ToString() +
            "\nbraking_energy_dissipated: " + braking_energy_dissipated.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
